# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d346d776c1c42246bfbfcc621220004bbb326d639d4b24e7dd9adf91849a876e2d31c02e3141f69f30cc4a169e857aa3351404e0ca65f6746f0de11e6a8ec2f1

test:
  secret_key_base: 69d70d55d128105f14e12c0a16c6cad8eb75704c9729cf0b4a43933ac4c3a2cbf5a85982dfda808c20959143aab237e3c6575e602a50641782622a32e2db15bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
